mkisofs.iso.level=3
mkisofs.rockridge.use=true
mkisofs.joliet.use=true
mkisofs.symlinks.follow=false
general.exit.confirm=true
jisocreator.language=en

mkisofs.unix.path=/usr/bin/mkisofs
mkisofs.win32.path=<mkisofs.base.path>\\res\\mkisofs\\mkisofs.exe